{{/* Check required values and define variables */}}
{{- $dockerRepository := .Values.required.image.repository | required ".Values.required.image.repository is required." -}}
{{- $dockerImage := .Values.required.image.name | required ".Values.required.image.name is required." -}}
{{- $dockerTag := .Values.required.image.tag | default .Chart.AppVersion -}}
{{- $dataImage := .Values.required.data.name | required ".Values.required.data.name is required." -}}
{{- $dataVersion := .Values.required.data.version | required ".Values.required.data.version is required." -}}
{{- $customEnvVars := .Values.customEnvVars -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-routing-service.fullversionname" . }}
  labels:
    {{- include "notification-routing-service.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "notification-routing-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "notification-routing-service.selectorLabels" . | nindent 8 }}
        {{- include "notification-routing-service.deploymentLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "notification-routing-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      # Mount Data
      volumes:
        - name: tmp-volume
          emptyDir: {}
        {{- if .Values.debug.enable }}
        - name: jfr-volume
          emptyDir: {}
        {{- end }}
        - name: routing-data-volume
          emptyDir: {}
      initContainers:
        - name: {{ .Chart.Name }}-init-data
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $dockerRepository }}/{{ $dataImage }}:{{ $dataVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/sh
            - -c
            - "cp -r /app/data/lookup/* /data"
          volumeMounts:
            - name: routing-data-volume
              mountPath: "/data"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $dockerRepository }}/{{ $dockerImage }}:{{ $dockerTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- /* If entrypoint and parameters are both defined, configure them */ -}}
          {{- if .Values.application.entrypoint }}
          {{- if .Values.application.parameters }}
          {{- with .Values.application.entrypoint }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.application.parameters }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- end }}
          # Set the Environment Variables for the container
          env:
            - name: "TZ"
              value: "Europe/Berlin"
            - name: "DATA_DIR_LOOKUP"
              value: {{ include "notification-routing-service.lookup-directory" . | quote }}
            {{- if eq (.Values.customEnvVars.FEATURE_FLAG_NEW_API_ENDPOINTS | toString) "true" }}
            - name: "NRS_CLIENT_FUTS_CONTEXT_PATH"
              value: "/"
            {{- end }}
            {{- if .Values.debug.enable }}
            - name: "JAVA_TOOL_OPTIONS"
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000"
            {{- end }}
            {{- if $customEnvVars }}
            # Custom Environment Variables
            {{- range $_, $key := keys $customEnvVars | sortAlpha }}
            - name: {{ $key | quote }}
              value: {{ get $customEnvVars $key | quote }}
            {{- end }}
            {{- end }}
          # Mount Volumes in container
          volumeMounts:
            - name: routing-data-volume
              mountPath: {{ include "notification-routing-service.lookup-directory" .| quote }}
              readOnly: true
            - name: tmp-volume
              mountPath: "/tmp"
            {{- if .Values.debug.enable }}
            - name: jfr-volume
              mountPath: "/jfrdump"
            {{- end }}
          # Ports to be exposed from the container
          ports:
            - name: nrs-port
              containerPort: 8080
              protocol: TCP
            {{- if .Values.debug.enable }}
            - name: debug-port
              containerPort: 9000
              protocol: TCP
            {{- end }}
          # Performs checks to verify that the application is successfully started
          # The Application is marked as failed after periodSeconds*failureThreshold seconds
          startupProbe:
            httpGet:
              path: /actuator/health
              port: nrs-port
            failureThreshold: 10
            periodSeconds: 30
          # Use SpringBoot Actuator Liveness Check
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: nrs-port
            failureThreshold: 3
            periodSeconds: 30
          # Use SpringBoot Actuator Readiness Check
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: nrs-port
            failureThreshold: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          # Define Limits and Requested Resources (CPU/RAM)
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "notification-routing-service.name" . }}
              - key: version
                operator: In
                values:
                - {{ .Chart.AppVersion | quote }}
            topologyKey: "kubernetes.io/hostname"
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
