{{- if not .Values.istio.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-routing-service.fullversionname" . }}
  labels:
    {{- include "notification-routing-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "notification-routing-service.selectorLabels" . | nindent 4 }}
{{- end }}