# Default values for notification-routing-service.

# Number of Pod Replicas desired
replicaCount: 2

# Enables debug mode
debug:
  enable: false

# Required Values for the Chart
required:
  # Define the docker image
  image:
    # The repository where is stored the docker image "notification-routing-service" and "notification-routing-data"
    repository: europe-west3-docker.pkg.dev/gematik-all-infra-prod/demis-dev
    # The name of the image
    name: notification-routing-service
    # Overrides the image tag whose default is the chart appVersion.
    # If not given, the Chart AppVersion will be used
    tag: null
  # Version of the profiles to be used
  data:
    name: notification-routing-data
    version: 1.3.0-b19

# Extra Labels to be added
# E.g.
# customLabels:
#   my-label: my-label-value
customLabels: {}

# Extra labels for deployments
deploymentLabels: {}

# Environment Variables to be defined
customEnvVars:
  FEATURE_FLAG_SEARCH_FUZZY: "false"
  FEATURE_FLAG_SEARCH_COMPARISON: "false"
  FEATURE_FLAG_NOTIFICATIONS_7_3: "false"
  FEATURE_FLAG_FOLLOW_UP_NOTIFICATIONS: "false"
  FEATURE_FLAG_TUBERCULOSIS_ROUTING_ENABLED: "false"

# Define custom Container Entrypoint and Arguments (e.g. JVM Tuning)
# If not given, the Entrypoint defined in Dockerfile will be used
application:
  entrypoint: ["java"]
  parameters: ["-XX:ActiveProcessorCount=2", "-XX:MaxRAMPercentage=80.0", "-XX:+TieredCompilation", "-XX:+UseSerialGC", "-jar", "/app.jar"]

# The Pull Policy for the Image
imagePullPolicy: IfNotPresent
# Define Image Pull Secrets if using private registry
imagePullSecrets: []
nameOverride: "notification-routing-service"
fullnameOverride: "notification-routing-service"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Annotations for Workload
annotations: {}

# Annotations for Pods
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8080"

# Pod Security Context - applies to all containers in a Pod
podSecurityContext:
  # The GID to tell the Kubelet to modify permissions of a volume owned by a pod
  fsGroup: 10000
  # Determines when to apply fsGroup actions - "Always" is the default
  fsGroupChangePolicy: "OnRootMismatch"
  # Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  # Which UID container process is assigned
  runAsUser: 10000

# Container Security Context for a single container - Takes precedence over PodSecurityContext
securityContext:
  #defines whether container can be granted privileges beyond the parent process spawing the process
  allowPrivilegeEscalation: false
  #Define whether the container has privileged access e.g. CAP_SYS_ADMIN capability and SELinux spc_t type
  privileged: false
  #Usually no longer required. Determines whether /proc is masked to the container. Do not mount /proc from a host to a container
  procMount: Default
  # The SELinux context to be applied to the container. Must not be explicitly set to Unconfined.
  seccompProfile:
    type: "RuntimeDefault"
  #Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  #Which UID container process is assigned
  runAsUser: 10000
  # Sets the file system as read-only
  readOnlyRootFilesystem: true
  #Ability to remove and /or add Linux Capabilities
  capabilities:
    drop:
    - all

service:
  type: ClusterIP
  ports:
    http: 8080

# Resources
resources:
  limits:
    memory: "650Mi"
  requests:
    cpu: "100m"
    memory: "650Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

istio:
  enable: true
  validateJwt: false
